[brick]
name = "quickchpl"
version = "1.0.0"
chplVersion = "2.6.0..2.7.0"
license = "MIT"
authors = ["Jess Sullivan <jess@sulliwood.org>"]
repository = "https://github.com/Jesssullivan/chplcheck"
description = "A simple property-based testing library for Chapel"
keywords = ["testing", "property-based", "quickcheck", "pbt", "fuzzing"]

[dependencies]
# No external dependencies - pure Chapel uWu

[dev-dependencies]
# chplcheck would be good here